export { AdminPanel } from "./Admin"
export { CatalogosPanel } from "./Catalogos"
export { CatastroPanel } from "./Catastro"
export { Login } from "./Login"
export { ReportesPanel } from "./Reportes"
export { RiegoPanel } from "./Riego"
export { SolicitudesPanel } from "./Solicitudes"
