import { expect, test } from "@playwright/test"

async function entrar(page: import("@playwright/test").Page, usuario: string) {
  await page.goto("/")
  await page.getByLabel("Usuario").fill(usuario)
  await page.getByLabel("Clave").fill("pando-local")
  await page.getByRole("button", { name: "Entrar" }).click()
}

test("capataz a 390 ve Hoy y no ve Catastro ni Inventario", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await entrar(page, "norte")
  await expect(page.getByRole("heading", { name: /Cuadrilla Norte/ })).toBeVisible()
  await expect(page.getByRole("button", { name: "Hoy", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Catastro", exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Áreas y sectores", exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Inventario", exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Más", exact: true })).toHaveCount(0)
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/capataz-hoy-390.png" })
})

test("capataz inicia una actividad y sin red ve el chip por enviar", async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await entrar(page, "norte")
  const iniciar = page.getByRole("button", { name: "Iniciar" }).first()
  await expect(iniciar).toBeVisible()
  await iniciar.click()
  await context.setOffline(true)
  await expect(page.getByText(/Sin conexión · \d+ por enviar/)).toBeVisible()
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/capataz-sin-conexion-390.png" })
  await context.setOffline(false)
})

test("jefatura no ve Guardar de catastro ni formularios de poda, vivero o riego", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await entrar(page, "jefatura")
  await page.getByRole("button", { name: "Áreas y sectores", exact: true }).click()
  const fila = page.locator(".catastro-editor .labor-list .labor").first()
  if (await fila.count()) await fila.click()
  await expect(page.getByRole("button", { name: "Guardar área" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Nueva área" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Guardar zona de supervisión" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Guardar referente" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Registros de campo" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Guardar poda" })).toHaveCount(0)
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/jefatura-sin-guardar-1280.png" })
})

test("la pestaña dice Administración y el historial distingue los roles", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await entrar(page, "admin")
  const admin = page.getByRole("button", { name: "Administración", exact: true })
  await expect(admin).toBeVisible()
  await expect(page.getByRole("button", { name: "Admin", exact: true })).toHaveCount(0)
  await admin.click()
  await expect(page.getByRole("heading", { name: "Nueva cuenta" })).toBeVisible()
  await page.getByRole("button", { name: "Historial", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Historial" })).toBeVisible()
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/admin-administracion-1280.png" })

  await page.getByRole("button", { name: "Salir" }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await entrar(page, "norte")
  await expect(page.getByRole("button", { name: "Historial", exact: true })).toHaveCount(0)
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/capataz-sin-historial-390.png" })
})

test("registros de campo abre el formulario solo con Nuevo registro", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await entrar(page, "coordinacion")
  await page.getByRole("button", { name: "Registros de campo", exact: true }).click()
  await expect(page.getByRole("tab", { name: "Riego" })).toHaveAttribute("aria-selected", "true")
  await expect(page.getByRole("tab", { name: "Poda" })).toBeVisible()
  await expect(page.getByRole("tab", { name: "Vivero" })).toBeVisible()
  await expect(page.locator("#riego select[name='sector_id']")).toHaveCount(0)
  await page.getByRole("button", { name: "Nuevo registro" }).click()
  await expect(page.locator("#riego select[name='sector_id']")).toBeVisible()
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/registros-campo-1280.png" })
})

test("el mapa muestra capas y leyenda sin abrir el panel", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await entrar(page, "coordinacion")
  await page.getByRole("button", { name: "Mapa", exact: true }).click()
  const control = page.getByRole("complementary", { name: "Capas" })
  await expect(control.getByRole("button", { name: "Plano" })).toBeVisible()
  await expect(control.getByRole("button", { name: "Relieve" })).toBeVisible()
  await expect(control.getByRole("button", { name: "Sector de capataz" })).toBeVisible()
  await expect(page.locator(".shell")).toHaveClass(/panel-off/)
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/mapa-capas-1280.png" })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/mapa-capas-390.png" })
})

test("el nombre del capataz se lee y el botón de ayuda toma el foco", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await entrar(page, "norte")
  await expect(page.getByText("Elsa Quispe")).toBeVisible()
  await expect(page.getByText("Capataz")).toBeVisible()
  const ayuda = page.getByRole("button", { name: "Qué significa Bloqueada" })
  await ayuda.focus()
  await expect(ayuda).toBeFocused()
  await page.screenshot({ path: "e2e-artifacts/o4-claridad/capataz-identidad-390.png" })
})
