import { expect, test } from "@playwright/test"

test("el mapa dice sectores de capataz y el editor elige el lugar en un select", async ({ page }) => {
  await page.goto("/")
  await page.getByLabel("Usuario").fill("admin")
  await page.getByLabel("Clave").fill("pando-local")
  await page.getByRole("button", { name: "Entrar" }).click()

  await expect(page.getByRole("status")).toContainText("sectores de capataz")
  await page.getByRole("button", { name: "Sector de capataz", exact: true }).click()
  await expect(page.getByText("Sector de capataz — Valeria Quispe (ficticio)")).toBeVisible()
  const vias = page.getByRole("checkbox", { name: /Vías/ })
  await vias.scrollIntoViewIfNeeded()
  await expect(vias).not.toBeChecked()
  await expect(page.getByRole("checkbox", { name: /sin archivo de cuarteles/ })).toBeVisible()
  await page.screenshot({ path: "/opt/cursor/artifacts/screenshots/mapa-sectores-capataz.png", fullPage: true })

  await page.getByRole("button", { name: "Áreas y sectores", exact: true }).click()
  await page.getByRole("button", { name: "Nueva área" }).click()
  const ficha = page.locator("form").filter({ has: page.getByRole("button", { name: "Guardar área" }) })
  const lugar = ficha.getByLabel("Lugar")
  await lugar.scrollIntoViewIfNeeded()
  await expect(lugar).toBeVisible()
  await expect(ficha.locator('select[name="lugar_id"]')).toBeVisible()
  await expect(ficha.locator('input[name="lugar"]')).toHaveCount(0)
  await expect(ficha.locator('input[name="lugar_libre"]')).toHaveCount(0)
  await page.screenshot({ path: "/opt/cursor/artifacts/screenshots/editor-selector-lugar.png" })
  const sectores = page.getByRole("heading", { name: "Sectores de capataz" })
  await sectores.scrollIntoViewIfNeeded()
  await expect(sectores).toBeVisible()
  const vacio = page.getByRole("complementary", { name: "Panel" }).getByText("sin archivo de cuarteles")
  await vacio.scrollIntoViewIfNeeded()
  await expect(vacio).toBeVisible()
  await page.screenshot({ path: "/opt/cursor/artifacts/screenshots/editor-sectores-capataz.png" })
})
